# Generated by Django 4.2.1 on 2023-05-25 07:46

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0006_alter_profile_address_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('nature_travail', models.CharField(blank=True, max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('date_travo', models.DateField()),
                ('ouvrier', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='blank-profile-picture.png', upload_to='post_images')),
                ('macon', models.IntegerField(blank=True, null=True)),
                ('manoeuvre', models.IntegerField(blank=True, null=True)),
                ('menuisier', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
