# Generated by Django 4.2.1 on 2023-05-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nature_travail',
            field=models.CharField(default='travail', max_length=100),
        ),
    ]
