# Generated by Django 4.2.1 on 2023-05-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0010_alter_post_nature_travail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ouvrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('valeur', models.IntegerField(default=0)),
            ],
        ),
    ]
