# Generated by Django 4.2.2 on 2023-07-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0012_metier_delete_ouvrier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='manoeuvre',
            new_name='nombreOuvrier',
        ),
        migrations.RemoveField(
            model_name='post',
            name='macon',
        ),
        migrations.RemoveField(
            model_name='post',
            name='menuisier',
        ),
        migrations.AddField(
            model_name='post',
            name='typeOuvrier',
            field=models.CharField(default=25, max_length=100),
            preserve_default=False,
        ),
    ]
